server:
  port: 8443
  ssl:
    key-store-type: pkcs12
    key-alias: tomcat
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://34.64.37.20:3306/mintalk?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    gcp:
      storage:
        credentials:
          location:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000

    show-sql: true
    open-in-view: false

user:
  timezone: Asia/Seoul
logging:
  level:
    org.hibernate.type: debug
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 5
  file:
    name:

