server:
  port: 8443
  ssl:
    key-store-type: pkcs12
    key-alias: tomcat
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://34.64.37.20:3306/mintalk?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000

    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace

